/* import the fontawesome core */
import { library } from "@fortawesome/fontawesome-svg-core";

/* import specific icons */
import {
  faLocationArrow,
  faMagnifyingGlass,
  faXmark,
  faLocationCrosshairs,
  faPlane,
  faTrademark,
  faChartBar,
  faTicket,
  faPlaneCircleExclamation,
  faLocationDot,
  faSquarePlus,
  faDeleteLeft,
  faList,
  faPlus,
  faTrash,
  faChevronLeft,
  faChevronRight,
  faRepeat,
  faEdit,
  faChartArea,
  faCalendarDays,
  faEarthAmericas,
  faCity,
  faCheckCircle,
  faExclamationTriangle,
  faMoneyBill,
  faCheck,
  faEnvelope,
  faRightToBracket,
  faUserPen,
  faUsersBetweenLines,
  faInfoCircle,
  faUserClock,
  faCreditCard,
} from "@fortawesome/free-solid-svg-icons";
import {
  faCopyright,
  faEye,
  faUser,
} from "@fortawesome/free-regular-svg-icons";
library.add(
  faLocationArrow,
  faLocationCrosshairs,
  faMagnifyingGlass,
  faXmark,
  faPlane,
  faTrademark,
  faChartBar,
  faTicket,
  faPlaneCircleExclamation,
  faLocationDot,
  faMagnifyingGlass,
  faSquarePlus,
  faDeleteLeft,
  faList,
  faPlus,
  faXmark,
  faTrash,
  faChevronRight,
  faChevronLeft,
  faRepeat,
  faEdit,
  faChartArea,
  faCalendarDays,
  faEarthAmericas,
  faCity,
  faCopyright,
  faCheckCircle,
  faExclamationTriangle,
  faMoneyBill,
  faEye,
  faUser,
  faCheck,
  faEnvelope,
  faRightToBracket,
  faUserPen,
  faUsersBetweenLines,
  faInfoCircle,
  faUserClock,
  faCreditCard
);
